# -*- coding: utf-8 -*-
"""Arabic overrides for tah_ch6.py's 50 questions, in the same order."""

SECTION_AR = {
    "Evaluating limits by direct substitution": "إيجاد النهايات بالتعويض المباشر",
    "Evaluating limits by factoring (the 0/0 form)": "إيجاد النهايات بالتحليل (الصورة 0/0)",
    "Limits at infinity": "النهايات عند اللانهاية",
    "One-sided limits": "النهايات من جهة واحدة",
    "The power rule": "قاعدة القوة",
    "The product rule": "قاعدة الضرب",
    "The chain rule": "قاعدة السلسلة",
    "Derivatives of trigonometric and exponential functions": "مشتقات الدوال المثلثية والأسية",
    "Tangent lines": "خطوط المماس",
    "Increasing, decreasing, and the second derivative": "التزايد والتناقص والمشتقة الثانية",
    "Word problems: rates of change": "مسائل لفظية: معدلات التغير",
}

OV = [
  {"q_ar": r"أوجد $\lim_{x\to3}(2x^2-5x+3)$.", "answer_ar": r"$2(9)-5(3)+3=18-15+3=6$."},
  {"q_ar": r"أوجد $\lim_{x\to-2}(x^3-3x+4)$.", "answer_ar": r"$(-2)^3-3(-2)+4=-8+6+4=2$."},
  {"q_ar": r"أوجد $\lim_{x\to1}\dfrac{4x+9}{x+5}$.", "answer_ar": r"$\dfrac{4(1)+9}{1+5}=\dfrac{13}{6}$."},
  {"q_ar": r"أوجد $\lim_{x\to6}\sqrt{x+10}$.", "answer_ar": r"$\sqrt{6+10}=\sqrt{16}=4$."},
  {"q_ar": r"أوجد $\lim_{x\to4}\dfrac{x^2-3x}{2x+1}$.", "answer_ar": r"$\dfrac{16-12}{9}=\dfrac{4}{9}$."},

  {"q_ar": r"أوجد $\lim_{x\to4}\dfrac{x^2-16}{x-4}$.", "answer_ar": r"$\dfrac{(x-4)(x+4)}{x-4}\to x+4=8$."},
  {"q_ar": r"أوجد $\lim_{x\to-3}\dfrac{x^2+7x+12}{x+3}$.", "answer_ar": r"$\dfrac{(x+3)(x+4)}{x+3}\to x+4=1$."},
  {"q_ar": r"أوجد $\lim_{x\to5}\dfrac{x^2-25}{x-5}$.", "answer_ar": r"$\dfrac{(x-5)(x+5)}{x-5}\to x+5=10$."},
  {"q_ar": r"أوجد $\lim_{x\to2}\dfrac{x^2-4}{x^2-5x+6}$.",
   "answer_ar": r"$\dfrac{(x-2)(x+2)}{(x-2)(x-3)}\to\dfrac{x+2}{x-3}=\dfrac{4}{-1}=-4$."},
  {"q_ar": r"أوجد $\lim_{x\to-1}\dfrac{x^2-1}{x^2+3x+2}$.",
   "answer_ar": r"$\dfrac{(x-1)(x+1)}{(x+1)(x+2)}\to\dfrac{x-1}{x+2}=\dfrac{-2}{1}=-2$."},

  {"q_ar": r"أوجد $\lim_{x\to\infty}\dfrac{4x^2+3x}{2x^2-7}$.", "answer_ar": r"نفس الدرجة: نسبة المعاملين الرئيسيين $=\dfrac{4}{2}=2$."},
  {"q_ar": r"أوجد $\lim_{x\to\infty}\dfrac{3x+5}{x^2+2}$.", "answer_ar": r"درجة المقام أعلى: النهاية $=0$."},
  {"q_ar": r"أوجد $\lim_{x\to\infty}\dfrac{7x^3-1}{x^3+3x}$.", "answer_ar": r"نفس الدرجة: نسبة المعاملين الرئيسيين $=\dfrac{7}{1}=7$."},
  {"q_ar": r"أوجد $\lim_{x\to\infty}\dfrac{2x^2+1}{5x^3-4}$.", "answer_ar": r"درجة المقام أعلى: النهاية $=0$."},

  {"q_ar": r"دالة معرّفة بـ$f(x)=x+2$ لـ$x<3$، و$f(x)=3x-4$ لـ$x\geq3$. أوجد $\lim_{x\to3^-}f(x)$.",
   "answer_ar": r"باستخدام $x<3$: $f(x)\to3+2=5$."},
  {"q_ar": r"باستخدام نفس الدالة المجزأة، أوجد $\lim_{x\to3^+}f(x)$.",
   "answer_ar": r"باستخدام $x\geq3$: $f(x)\to3(3)-4=5$."},
  {"q_ar": r"باستخدام نفس الدالة المجزأة، هل توجد $\lim_{x\to3}f(x)$؟ اذكر قيمتها.",
   "answer_ar": r"بما أن النهايتين من اليسار واليمين تساويان $5$، فإن النهاية الثنائية الاتجاه موجودة وتساوي $5$.",
   "choices_ar_pre": ["نعم، تساوي $5$", "لا، غير موجودة", "نعم، تساوي $4$", "نعم، تساوي $9$"]},
  {"q_ar": r"دالة معرّفة بـ$f(x)=2x$ لـ$x\leq1$، و$f(x)=x+3$ لـ$x>1$. أوجد $\lim_{x\to1^-}f(x)$.",
   "answer_ar": r"باستخدام $x\leq1$: $f(x)\to2(1)=2$."},
  {"q_ar": r"باستخدام نفس الدالة المجزأة، أوجد $\lim_{x\to1^+}f(x)$، وحدد هل توجد $\lim_{x\to1}f(x)$.",
   "answer_ar": r"النهاية من اليمين $=1+3=4$. بما أن النهاية من اليسار ($2$) تختلف عن اليمين ($4$)، فإن النهاية الثنائية الاتجاه غير موجودة.",
   "choices_ar_pre": ["$4$؛ غير موجودة", "$4$؛ موجودة", "$2$؛ موجودة", "$2$؛ غير موجودة"]},

  {"q_ar": r"اشتق $f(x)=x^7$.", "answer_ar": r"قاعدة القوة: $7x^{7-1}=7x^6$."},
  {"q_ar": r"اشتق $f(x)=4x^5-3x^3+2x$.", "answer_ar": r"اشتق كل حد: $20x^4-9x^2+2$."},
  {"q_ar": r"اشتق $f(x)=\sqrt{x}$.", "answer_ar": r"$f(x)=x^{1/2}\Rightarrow f'(x)=\dfrac{1}{2}x^{-1/2}=\dfrac{1}{2\sqrt{x}}$."},
  {"q_ar": r"اشتق $f(x)=\dfrac{1}{x^3}$.", "answer_ar": r"$f(x)=x^{-3}\Rightarrow f'(x)=-3x^{-4}=-\dfrac{3}{x^4}$."},
  {"q_ar": r"اشتق $f(x)=6x^2-4x+9$.", "answer_ar": r"اشتق كل حد: $12x-4$."},

  {"q_ar": r"اشتق $f(x)=x^3(2x+5)$ باستخدام قاعدة الضرب.",
   "answer_ar": r"$f'(x)=3x^2(2x+5)+x^3(2)=6x^3+15x^2+2x^3=8x^3+15x^2$."},
  {"q_ar": r"اشتق $f(x)=(x+3)(x-7)$ باستخدام قاعدة الضرب.", "answer_ar": r"$f'(x)=(x-7)+(x+3)=2x-4$."},
  {"q_ar": r"اشتق $f(x)=(3x-2)(x^2+4)$ باستخدام قاعدة الضرب.",
   "answer_ar": r"$f'(x)=3(x^2+4)+(3x-2)(2x)=3x^2+12+6x^2-4x=9x^2-4x+12$."},
  {"q_ar": r"اشتق $f(x)=(x^2+1)(x^2-1)$ باستخدام قاعدة الضرب.",
   "answer_ar": r"$f'(x)=2x(x^2-1)+(x^2+1)(2x)=2x^3-2x+2x^3+2x=4x^3$."},
  {"q_ar": r"اشتق $f(x)=x^2(x^3-4)$ باستخدام قاعدة الضرب.",
   "answer_ar": r"$f'(x)=2x(x^3-4)+x^2(3x^2)=2x^4-8x+3x^4=5x^4-8x$."},

  {"q_ar": r"اشتق $f(x)=(2x+3)^5$.", "answer_ar": r"$f'(x)=5(2x+3)^4\cdot2=10(2x+3)^4$."},
  {"q_ar": r"اشتق $f(x)=(x^2-3)^4$.", "answer_ar": r"$f'(x)=4(x^2-3)^3\cdot2x=8x(x^2-3)^3$."},
  {"q_ar": r"اشتق $f(x)=\sqrt{5x+1}$.", "answer_ar": r"$f'(x)=\dfrac{1}{2\sqrt{5x+1}}\cdot5=\dfrac{5}{2\sqrt{5x+1}}$."},
  {"q_ar": r"اشتق $f(x)=(4-3x)^5$.", "answer_ar": r"$f'(x)=5(4-3x)^4\cdot(-3)=-15(4-3x)^4$."},
  {"q_ar": r"اشتق $f(x)=(x^3+2)^2$.", "answer_ar": r"$f'(x)=2(x^3+2)\cdot3x^2=6x^2(x^3+2)$."},

  {"q_ar": r"اشتق $f(x)=\cos x-\sin x$.", "answer_ar": r"$\dfrac{d}{dx}[\cos x]=-\sin x$، $\dfrac{d}{dx}[-\sin x]=-\cos x$."},
  {"q_ar": r"اشتق $f(x)=5\cos x$.", "answer_ar": r"$\dfrac{d}{dx}[5\cos x]=-5\sin x$."},
  {"q_ar": r"اشتق $f(x)=e^x-x^3$.", "answer_ar": r"$\dfrac{d}{dx}[e^x]=e^x$، $\dfrac{d}{dx}[-x^3]=-3x^2$."},
  {"q_ar": r"اشتق $f(x)=2e^x+\sin x$.", "answer_ar": r"$\dfrac{d}{dx}[2e^x]=2e^x$، $\dfrac{d}{dx}[\sin x]=\cos x$."},

  {"q_ar": r"أوجد ميل خط المماس لـ$f(x)=x^2$ عند $x=4$.", "answer_ar": r"$f'(x)=2x$؛ $f'(4)=8$."},
  {"q_ar": r"أوجد معادلة خط المماس لـ$f(x)=x^2$ عند $x=3$.",
   "answer_ar": r"$f(3)=9$، $f'(3)=6$: $y-9=6(x-3)\Rightarrow y=6x-9$."},
  {"q_ar": r"يوضح الرسم البياني $f(x)=x^2-2x$، مع تحديد النقطة عند $x=3$. أوجد معادلة خط المماس هناك.",
   "answer_ar": r"$f(3)=3$، $f'(3)=4$: $y-3=4(x-3)\Rightarrow y=4x-9$."},
  {"q_ar": r"أوجد قيم $x$ التي يكون عندها المماس لـ$f(x)=x^3-12x$ أفقيًا.",
   "answer_ar": r"$f'(x)=3x^2-12=0\Rightarrow x^2=4\Rightarrow x=\pm2$.",
   "choices_ar_pre": ["$x=2$ و$x=-2$", "$x=4$ و$x=-4$", "$x=2$ فقط", "$x=0$"]},
  {"q_ar": r"يوضح الرسم البياني $f(x)=x^2$ وخط مماسه عند $x=2$. أوجد ميل خط المماس بقراءة الرسم البياني.",
   "answer_ar": r"يرتفع خط المماس $4$ لكل $1$ أفقيًا."},

  {"q_ar": r"لـ$f(x)=x^2-6x+3$، أوجد $f'(x)$ وحدد الفترة التي تكون فيها $f$ متزايدة.",
   "answer_ar": r"$f'(x)=2x-6>0\Rightarrow x>3$.",
   "choices_ar_pre": [r"$f'(x)=2x-6$؛ متزايدة لـ$x>3$", r"$f'(x)=2x-6$؛ متزايدة لـ$x<3$",
                       r"$f'(x)=2x$؛ متزايدة لـ$x>3$", r"$f'(x)=2x-6$؛ متزايدة لـ$x>6$"]},
  {"q_ar": r"لـ$f(x)=-x^2+8x$، حدد الفترة التي تكون فيها $f$ متناقصة.", "answer_ar": r"$f'(x)=-2x+8<0\Rightarrow x>4$."},
  {"q_ar": r"أوجد المشتقة الثانية لـ$f(x)=x^5-3x^3$.", "answer_ar": r"$f'(x)=5x^4-9x^2$؛ $f''(x)=20x^3-18x$."},
  {"q_ar": r"أوجد المشتقة الثانية لـ$f(x)=x^4+2x^2$.", "answer_ar": r"$f'(x)=4x^3+4x$؛ $f''(x)=12x^2+4$."},

  {"q_ar": r"ارتفاع كرة قُذفت للأعلى معطى بـ$h(t)=-5t^2+30t+3$ (بالمتر). أوجد سرعة الكرة عند $t=2$ ثانية.",
   "answer_ar": r"$h'(t)=-10t+30$؛ $h'(2)=10$ م/ث."},
  {"q_ar": r"تكلفة إنتاج شركة لـ$x$ قطعة هي $C(x)=0.02x^2+8x+150$ (بالدولار). أوجد التكلفة الحدية عند $x=100$.",
   "answer_ar": r"$C'(x)=0.04x+8$؛ $C'(100)=12$.",
   "choices_ar_pre": ["$12$ دولارًا", "$8$ دولارات", "$4$ دولارات", "$20$ دولارًا"]},
  {"q_ar": r"ارتفاع كرة قُذفت للأعلى معطى بـ$h(t)=-5t^2+30t+3$ (بالمتر). أوجد الزمن الذي تصل عنده الكرة إلى أقصى ارتفاع.",
   "answer_ar": r"$h'(t)=-10t+30=0\Rightarrow t=3$ ثوانٍ."},
]

assert len(OV) == 50, f"expected 50 overrides, got {len(OV)}"
