# -*- coding: utf-8 -*-
"""Arabic overrides for tah_ch8.py's 50 questions, in the same order."""

SECTION_AR = {
    "Evaluating exponential expressions": "تقييم المقادير الأسية",
    "Evaluating logarithms": "تقييم اللوغاريتمات",
    "Log laws: product and quotient": "قوانين اللوغاريتمات: الضرب والقسمة",
    "Log laws: the power rule": "قوانين اللوغاريتمات: قاعدة القوة",
    "Expanding and condensing logarithmic expressions": "فك وتكثيف المقادير اللوغاريتمية",
    "Solving exponential equations (matching bases)": "حل المعادلات الأسية (بمطابقة الأساسات)",
    "Solving exponential equations using logarithms": "حل المعادلات الأسية باستخدام اللوغاريتمات",
    "Solving logarithmic equations": "حل المعادلات اللوغاريتمية",
    "Natural logarithms and e": "اللوغاريتمات الطبيعية والعدد e",
    "Exponential growth and decay models": "نماذج النمو والتناقص الأسي",
    "Word problems: exponential models in context": "مسائل لفظية: النماذج الأسية في سياقها",
}

OV = [
  {"q_ar": r"أوجد $3^4$.", "answer_ar": r"$3^4=81$."},
  {"q_ar": r"أوجد $4^{-2}$.", "answer_ar": r"$4^{-2}=\dfrac{1}{4^2}=\dfrac{1}{16}$."},
  {"q_ar": r"أوجد $25^{1/2}$.", "answer_ar": r"$25^{1/2}=\sqrt{25}=5$."},
  {"q_ar": r"أوجد $8^{2/3}$.", "answer_ar": r"$8^{2/3}=(8^{1/3})^2=2^2=4$."},
  {"q_ar": r"أوجد $2^{-3}$.", "answer_ar": r"$2^{-3}=\dfrac{1}{2^3}=\dfrac{1}{8}$."},
  {"q_ar": r"أوجد $32^{3/5}$.", "answer_ar": r"$32^{3/5}=(32^{1/5})^3=2^3=8$."},

  {"q_ar": r"أوجد $\log_3 27$.", "answer_ar": r"$3^3=27$."},
  {"q_ar": r"أوجد $\log_2 64$.", "answer_ar": r"$2^6=64$."},
  {"q_ar": r"أوجد $\log_7 1$.", "answer_ar": r"$7^0=1$.",
   "choices_ar_pre": ["$0$", "$1$", "$7$", "غير معرّف"]},
  {"q_ar": r"أوجد $\log_{10}0.001$.", "answer_ar": r"$10^{-3}=0.001$."},
  {"q_ar": r"أوجد $\log_4 16$.", "answer_ar": r"$4^2=16$."},
  {"q_ar": r"أوجد $\log_5 125$.", "answer_ar": r"$5^3=125$."},

  {"q_ar": r"اكتب $\log_3(9x)$ كمجموع لوغاريتمات.", "answer_ar": r"$\log_3(9x)=\log_3 9+\log_3 x=2+\log_3 x$.",
   "choices_ar_pre": [r"$2+\log_3 x$", r"$\log_3 9+\log_3 x$ فقط", r"$9+\log_3 x$", r"$2\log_3 x$"]},
  {"q_ar": r"اكتب $\log_5\left(\dfrac{x}{25}\right)$ كفرق لوغاريتمات.",
   "answer_ar": r"$\log_5\left(\dfrac{x}{25}\right)=\log_5 x-\log_5 25=\log_5 x-2$."},
  {"q_ar": r"اجمع $\log_2 4+\log_2 8$ في لوغاريتم واحد وأوجد قيمته.", "answer_ar": r"$\log_2(4\times8)=\log_2 32=5$."},
  {"q_ar": r"اجمع $\log_3 54-\log_3 2$ في لوغاريتم واحد وأوجد قيمته.", "answer_ar": r"$\log_3(54\div2)=\log_3 27=3$."},

  {"q_ar": r"اكتب $\log(x^7)$ باستخدام قاعدة القوة.", "answer_ar": r"قاعدة القوة: $\log(x^n)=n\log x$.",
   "choices_ar_pre": [r"$7\log x$", r"$x^7\log x$", r"$\log x^7$ دون تغيير", r"$\log(7x)$"]},
  {"q_ar": r"أوجد $\log_3(9^2)$ باستخدام قاعدة القوة.", "answer_ar": r"$2\log_3 9=2(2)=4$."},
  {"q_ar": r"اكتب $3\log_2 x+\log_2 y$ كلوغاريتم واحد.",
   "answer_ar": r"$3\log_2 x=\log_2(x^3)$؛ بالدمج مع $\log_2 y$: $\log_2(x^3y)$."},
  {"q_ar": r"اكتب $4\log x-\log y$ كلوغاريتم واحد.", "answer_ar": r"$4\log x=\log(x^4)$؛ بالدمج: $\log\left(\dfrac{x^4}{y}\right)$."},

  {"q_ar": r"افك $\log\left(\dfrac{x^2y}{z^3}\right)$ بالكامل.",
   "answer_ar": r"بتطبيق قاعدتي القسمة والقوة: $2\log x+\log y-3\log z$.",
   "choices_ar_pre": [r"$2\log x+\log y-3\log z$", r"$2\log x+\log y+3\log z$",
                       r"$\log x^2+\log y-\log z^3$ دون تغيير", r"$2\log x-\log y-3\log z$"]},
  {"q_ar": r"كثّف $2\ln x-3\ln y$ في لوغاريتم واحد.",
   "answer_ar": r"$2\ln x=\ln(x^2)$، $3\ln y=\ln(y^3)$: $\ln\left(\dfrac{x^2}{y^3}\right)$."},
  {"q_ar": r"افك $\log_2\left(\sqrt{x}\cdot y^4\right)$ بالكامل.",
   "answer_ar": r"$\sqrt{x}=x^{1/2}$: $\dfrac{1}{2}\log_2 x+4\log_2 y$.",
   "choices_ar_pre": [r"$\dfrac{1}{2}\log_2 x+4\log_2 y$", r"$2\log_2 x+4\log_2 y$",
                       r"$\dfrac{1}{2}\log_2 x+\log_2 y^4$ دون تغيير", r"$\dfrac{1}{4}\log_2 x+2\log_2 y$"]},
  {"q_ar": r"كثّف $\dfrac{1}{2}\log x+2\log y$ في لوغاريتم واحد.",
   "answer_ar": r"$\dfrac{1}{2}\log x=\log\sqrt{x}$؛ بالدمج: $\log(\sqrt{x}\cdot y^2)$."},

  {"q_ar": r"حل $2^x=64$.", "answer_ar": r"$2^6=64$."},
  {"q_ar": r"حل $3^{x+2}=27$.", "answer_ar": r"$3^{x+2}=3^3\Rightarrow x+2=3\Rightarrow x=1$."},
  {"q_ar": r"حل $5^{3x}=125$.", "answer_ar": r"$5^{3x}=5^3\Rightarrow3x=3\Rightarrow x=1$."},
  {"q_ar": r"حل $4^x=\dfrac{1}{16}$.", "answer_ar": r"$4^x=4^{-2}\Rightarrow x=-2$."},
  {"q_ar": r"حل $2^{2x-1}=32$.", "answer_ar": r"$2^{2x-1}=2^5\Rightarrow2x-1=5\Rightarrow x=3$."},

  {"q_ar": r"حل $2^x=12$ لـ$x$، مقربًا لثلاث منازل عشرية.", "answer_ar": r"$x=\dfrac{\ln12}{\ln2}\approx3.585$."},
  {"q_ar": r"حل $7^x=50$ لـ$x$، مقربًا لثلاث منازل عشرية.", "answer_ar": r"$x=\dfrac{\ln50}{\ln7}\approx2.010$."},
  {"q_ar": r"حل $4^{2x}=90$ لـ$x$، مقربًا لثلاث منازل عشرية.",
   "answer_ar": r"$2x=\dfrac{\ln90}{\ln4}\approx3.246\Rightarrow x\approx1.623$."},
  {"q_ar": r"حل $e^x=25$ لـ$x$، مقربًا لثلاث منازل عشرية.", "answer_ar": r"$x=\ln25\approx3.219$."},

  {"q_ar": r"حل $\log_3(x)=4$.", "answer_ar": r"$3^4=81$."},
  {"q_ar": r"حل $\log_2(x-1)=3$.", "answer_ar": r"$x-1=2^3=8\Rightarrow x=9$."},
  {"q_ar": r"حل $\log(x)+\log(x-3)=1$.",
   "answer_ar": r"$\log(x(x-3))=1\Rightarrow x^2-3x-10=0\Rightarrow(x-5)(x+2)=0$؛ فقط $x=5$ يُبقي اللوغاريتمين معرّفين."},
  {"q_ar": r"حل $\log_2(x+2)+\log_2(x-2)=5$.",
   "answer_ar": r"$(x+2)(x-2)=2^5=32\Rightarrow x^2-4=32\Rightarrow x^2=36$؛ فقط $x=6$ يُبقي اللوغاريتمين معرّفين."},

  {"q_ar": r"أوجد $\ln(e^5)$.", "answer_ar": r"$\ln(e^x)=x$."},
  {"q_ar": r"أوجد $\ln\left(\dfrac{1}{e}\right)$.", "answer_ar": r"$\ln(e^{-1})=-1$."},
  {"q_ar": r"حل $\ln(x)=3$ لـ$x$، بدلالة $e$.", "answer_ar": r"$\ln(x)=3\Rightarrow x=e^3$."},
  {"q_ar": r"أوجد $e^{\ln7}$.", "answer_ar": r"$e^{\ln x}=x$."},

  {"q_ar": r"يُمثَّل عدد سكان بلدة بالدالة $P(t)=8{,}000e^{0.025t}$، حيث $t$ بالسنوات. أوجد $P(15)$، مقربًا لأقرب عدد صحيح.",
   "answer_ar": r"$P(15)=8{,}000e^{0.375}\approx11{,}640$."},
  {"q_ar": r"تتحلل مادة مشعة وفق $A(t)=150e^{-0.04t}$ (بالغرام). أوجد $A(25)$، مقربًا لمنزلة عشرية واحدة.",
   "answer_ar": r"$A(25)=150e^{-1}\approx55.2$ غ."},
  {"q_ar": r"حدد ما إذا كانت $N(t)=80e^{-0.015t}$ تمثّل نموًا أم تناقصًا.",
   "answer_ar": r"معامل الأس سالب: تناقص.",
   "choices_ar_pre": ["تناقص", "لا هذا ولا ذاك", "نمو", "لا يمكن تحديد ذلك"]},
  {"q_ar": r"حدد ما إذا كانت $M(t)=30e^{0.01t}$ تمثّل نموًا أم تناقصًا.",
   "answer_ar": r"معامل الأس موجب: نمو.",
   "choices_ar_pre": ["لا هذا ولا ذاك", "لا يمكن تحديد ذلك", "تناقص", "نمو"]},
  {"q_ar": r"يوضح الرسم البياني دالة أسية. بناءً على الرسم البياني، هل يمثّل نموًا أم تناقصًا؟",
   "answer_ar": r"يرتفع المنحنى مع زيادة $x$: نمو.",
   "choices_ar_pre": ["لا هذا ولا ذاك", "نمو", "لا يمكن تحديد ذلك", "تناقص"]},

  {"q_ar": r"ينمو استثمار قدره 3,000 دولار وفق $A(t)=3{,}000e^{0.05t}$ دولارًا، حيث $t$ بالسنوات. أوجد قيمة الاستثمار بعد 8 سنوات، مقربًا لأقرب دولار.",
   "answer_ar": r"$A(8)=3{,}000e^{0.4}\approx4{,}475$ دولارًا."},
  {"q_ar": r"يبرد كوب قهوة وفق $T(t)=22+70e^{-0.08t}$ (°م)، حيث $t$ بالدقائق. أوجد درجة الحرارة بعد 15 دقيقة، مقربًا لمنزلة عشرية واحدة.",
   "answer_ar": r"$T(15)=22+70e^{-1.2}\approx43.1$°م.",
   "choices_ar_pre": [r"$38.5$°م", r"$50.0$°م", r"$43.1$°م", r"$22.0$°م"]},
  {"q_ar": r"يتضاعف عدد بكتيريا كل 3 ساعات، بدءًا من 500. باستخدام $P(t)=500\cdot2^{t/3}$، أوجد العدد بعد 9 ساعات.",
   "answer_ar": r"$P(9)=500\times2^3=4{,}000$."},
  {"q_ar": r"تنخفض قيمة سيارة وفق $V(t)=25{,}000(0.85)^t$ دولارًا، حيث $t$ بالسنوات. أوجد قيمة السيارة بعد 5 سنوات، مقربًا لأقرب دولار.",
   "answer_ar": r"$V(5)=25{,}000(0.85)^5\approx11{,}093$ دولارًا."},
]

assert len(OV) == 50, f"expected 50 overrides, got {len(OV)}"
